[package]
name = "arch_gba"
version = "0.1.0"
authors = ["fhools <fhools@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
arm7tdmi = { path = "../arm7tdmi", version = "0.1.0" }
